POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Event",
    "details": "null",
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/e247fa61-3f08-4e1e-b8e0-8d2d9e6538a0/attendees
Content-Type: application/json

{
    "name": "Sarah",
    "email": "sarahhh@email.com"
}