POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Evento",
    "details": "null",
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/66cd56c9-de43-465f-a652-2882414edda4/attendees
Content-Type: application/json

{
    "name": "Sarah",
    "email": "sarahh@email.com"
}

###
GET http://localhost:3333/events/66cd56c9-de43-465f-a652-2882414edda4